[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "editor_sped"
version = "0.0.1"
dependencies = []
requires-python = ">=3.7"

[project.optional-dependencies]
TEST = [
    "autopep8",
    "pylint",
    "pytest",
    "pytest-pylint",
    "pytest-pep8",
    "pytest-cov"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.autopep8]
max_line_length = 160
ignore = ["E303"]

[tool.pylint]
max-line-length = 160
max-attributes = 15
disable = ["C0114", "C0115", "C0116"]
